let userData = [
  {
    tasks: [
      {
        id: 1,
        name: "React task 1",
        description: "Sample description",
        github: "",
        deployment: "",
        userComments: "",
        grade: null,
        mentorComments: "",
        createdAt: "",
        submittedAt: "",
      },
      {
        id: 2,
        name: "React task 2",
        description: "Sample description",
        github: "",
        deployment: "",
        userComments: "",
        grade: null,
        mentorComments: "",
        createdAt: "",
        submittedAt: "",
      },
      {
        id: 3,
        name: "React task 3",
        description: "Sample description",
        github: "",
        deployment: "",
        userComments: "",
        grade: null,
        mentorComments: "",
        createdAt: "",
        submittedAt: "",
      },
      {
        id: 4,
        name: "Node task 1",
        description: "Sample description",
        github: "",
        deployment: "",
        userComments: "",
        grade: null,
        mentorComments: "",
        createdAt: "",
        submittedAt: "",
      },
      {
        id: 5,
        name: "Node task 2",
        description: "Sample description",
        github: "",
        deployment: "",
        userComments: "",
        grade: null,
        mentorComments: "",
        createdAt: "",
        submittedAt: "",
      },
      {
        id: 6,
        name: "Node task 3",
        description: "Sample description",
        github: "",
        deployment: "",
        userComments: "",
        grade: null,
        mentorComments: "",
        createdAt: "",
        submittedAt: "",
      },
    ],
  },
  {
    queries: [
      {
        id: "SR-5626",
        title: "Cookie and localstorage ",
        description: "Sample description",
        status: "active",
        mentor: "",
        createdAt: "2021-09-25 13:40",
      },
    ],
  },
];

module.exports = userData;
